site_name: Spartan Documentation
pages:
    - Home: index.md
    - Getting Started: getting_started.md
    - Managing Data: managing_data.md
    - FAQ: faq.md
google_analytics: ['UA-97236408-1', 'auto']